accounts/urls.py
from django.urls import path
from .views import login_view, register_view, logout_view
from django.contrib.auth import views as auth_views


app_name = "accounts"
urlpatterns = [
    path('login/', login_view, name='login'),
    path('signup/', register_view, name='signup'),
    path('logout/', logout_view, name = 'logout'),

    
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"), name='reset_password'),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"), name='password_reset_confirm'),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"), name='password_reset_complete'),
]

my_cms_team_12/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

pages/urls.py
from django.urls import path
from .views import about_view, homepage_view

app_name = "pages"
urlpatterns =[
    path('home/', homepage_view, name="home"),
    path('about/', about_view, name="about"),

]

portfolia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('dashboard.urls')),
    path('', include('template_gallery.urls')),
    path('pages/', include('pages.urls')),
    path('documentation/', include('documentation.urls')),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


# Create your models here.

class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=200, null=True, verbose_name='first name')
    last_name = models.CharField(max_length=200, null=True, verbose_name='last name')
    avatar = models.ImageField(null=True, default= "avatar.svg")
    

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.first_name+" "+self.last_name

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    
    class Meta:
        model = CustomUser
        fields = ('email',)

    
class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email',)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from validate_email import validate_email
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate, login, logout

# Create your views here.

User = get_user_model()

def register_view(request):

    if request.method == 'POST':
        data = request.POST
        context={
        'has_error':False
        }
        email = request.POST.get('email', None)
        first_name = request.POST.get('first_name', None)
        last_name = request.POST.get('last_name', None)
        password = request.POST.get('password', None)
        password2 = request.POST.get('password2', None)

        if len(password) < 6:
            messages.add_message(request, messages.ERROR, 'Passwords should be at least 6 characters long')
            context['has_error'] = True

        if password!=password2:
            messages.add_message(request, messages.ERROR, 'Passwords do not match')
            context['has_error'] = True

        if not validate_email(email):
            messages.add_message(request, messages.ERROR, 'please provide a valid email')
            context['has_error'] = True


        try:
            if User.objects.get(email=email).exists():
                messages.add_message(request, messages.ERROR, 'Email is taken')
                context['has_error'] = True

        except Exception as identifier:
            pass 

        # if User.objects.filter(email=email).exists():
        #     messages.add_message(request, messages.ERROR, 'Email is taken')
        #     context['has_error'] = True

        if context['has_error']:
            return render(request, 'accounts/signup.html', context, status=400)
        
        user = User.objects.create_user(email=email, password=None)
        user.set_password(password)
        user.first_name = first_name
        user.last_name = last_name
        user.save()

        messages.add_message(request, messages.SUCCESS, 'Account created successfully')

        return redirect('pages:home')
    return render(request, 'accounts/signup.html')

def login_view(request):
    if request.user.is_authenticated:
        return redirect('dashboard')


    if request.method =='POST':
        context={
        'has_error':False
        }
        email = request.POST.get('email').lower()
        password = request.POST.get('password')
        if email == '':
            messages.add_message(request, messages.ERROR, 'email is required')
            context['has_error'] = True
        
        if password == '':
            messages.add_message(request, messages.ERROR, 'password is required')
            context['has_error'] = True
        
        user = authenticate(request, email=email, password=password)

        if not user and not context['has_error']:
            messages.add_message(request, messages.ERROR, 'invalid login credentials')
            context['has_error'] = True

        if context['has_error']:
            return render(request, 'accounts/login.html', status=401, context=context)
        
        login(request, user)
        return redirect('pages:home')
    return render(request, 'accounts/login.html')



def logout_view(request):
    logout(request)
    return redirect('login')
        

accounts/templates/accounts/login.html
{% load static %}
{% load socialaccount %}
{% providers_media_js %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'accounts/css/login.css' %}" type= "text/css">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
</head>
<body>
    <header>
        <div class="nav">
            <a href="{% url 'index' %}" class="back-link"><img src="{% static 'accounts/images/back_icon.svg'%}" alt="back_icon"></a>
            <a href="{% url 'accounts:signup' %}" class="signup-link">Create Account</a>
        </div>
    </header>
    <main>
        <div class="logo">
            <img src="{% static 'accounts/images/logo_1.svg' %}" alt="portfolia logo">
        </div>

        <h3 id="header">Log into Portfolia</h3>

        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                    {{ message|safe }}
                    <a href="{% url 'accounts:login' %}" class="close">x</a>
                </li>
            {% endfor %}
        </ul>
        {% endif %}
        
        <div class="form-container">
            <form action="#" method="POST">
                {% csrf_token %}
                <label for="email" >Email</label><br>
                <input type="email" placeholder="name@email.com" name ="email" id="email" required><br>

                <label for="password" >Password</label><br>
                <input type="password" placeholder="Password" name ="password" id="password" required><br>
            
                <input type="submit" value="Log In">
            </form>
            
            <div class="vertical-line1"></div>
            <span>Or</span>
            <!-- <div class="vertical-line2"></div> -->

            <div class="btn-container">
                <div class="gbtn-container">
                    <button class="google-btn" ><img src="{% static 'accounts/images/google_icon.svg' %}" alt="google-icon"><a href="{% provider_login_url 'google' method = 'oauth2' %}">Continue with Google</a></button>
                </div>
            
                <div class="fbtn-container">
                    <button class="facebook-btn"><img src="{% static 'accounts/images/facebook_icon.svg' %}" alt="facebook-icon"><a href="{% provider_login_url 'facebook' method = 'js_sdk' %}">Continue with Facebook</a></button>
                </div>
            </div>
            
    
        </div>

        <p class="cant-login"><a href="{% url 'accounts:reset_password' %}" >Can't Login?</a></p>
        <p class="captcha">Secure Login with reCAPTCHA subject to <a href="#">Google Terms</a> & <a href="#">Privacy</a></p>



    </main>
</body>
</html>

accounts/templates/accounts/password_reset.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Password</title>
    <link rel="stylesheet" href="{% static 'accounts/css/password_reset.css' %}" type= "text/css">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
</head>
<body>
    <header>
        <div class="nav">
            <a href="{% url 'accounts:login' %}" class="back-link"><img src="{% static 'accounts/images/back_icon.svg' %}" alt="back_icon"></a>
            <a href="{% url 'accounts:login' %}" class="signup-link">Log In</a>
        </div>
    </header>
    <main>
        <h3 id="header">Forgot Password</h3>
        <p>Enter your accounts's email and we will send you an email to reset your password</p>
        <div class="form-container">
            <form action="" method="POST">
                {% csrf_token %} 
                {% comment %} <label for="email" >Email</label><br>

                <input type="email" placeholder="name@email.com" name ="email" id="email" required><br> {% endcomment %}
                {{form}}

                <input type="submit" value="Send mail"> 

            </form>
        </div>
    </main>
</body>
</html>       
    

accounts/templates/accounts/password_reset_done.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset done</title>
    <link rel="stylesheet" href="{% static 'accounts/css/password_reset_done.css' %}" type= "text/css">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
</head>
<body>
    <header>
        <div class="nav">
            <a href="{% url 'accounts:login' %}" class="login-link">Log In</a>
        </div>
        <p>Your password has been set. You may go ahead and log in now </p>
    </header>

accounts/templates/accounts/password_reset_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Password</title>
    <link rel="stylesheet" href="{% static 'accounts/css/password_reset_form.css' %}" type= "text/css">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
</head>
<body>
    <main>
        <h3 id="header">Enter new password</h3>
        <p>Please enter your new password twice so we can verify you typed it in correctly</p>
        <div class="form-container">
            <form action="" method="POST">
                {% csrf_token %} 
                {% comment %} <label for="Password" >Password</label><br>

                <input type="password"  name ="password" id="password" required><br>

                <label for="Password" >Confirm Password</label><br>

                <input type="password"  name ="password" id="password" required><br> {% endcomment %}
                {{form}}

                <input type="submit" value="Update password">

            </form>
        </div>
    </main>
</body>

accounts/templates/accounts/password_reset_sent.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email sent</title>
    <link rel="stylesheet" href="{% static 'accounts/css/password_reset_sent.css' %}" type= "text/css">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
</head>
<body>
    <header>
        <div class="nav">
            <a href="{% url 'password_reset' %}" class="back-link"><img src="{% static 'accounts/images/back_icon.svg' %}" alt="back_icon"></a>
        </div>
    </header>

    <main>
        <p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should recieve them shortly. If you don't recieve an email, please make sure you've entered the address you registered with and check your spam folder.</p>
    </main>
</body

accounts/templates/accounts/signup.html
{% load static %}
{% load socialaccount %}
{% providers_media_js %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup</title>
    <link rel="stylesheet" href="{% static 'accounts/css/signup.css' %}" type= "text/css">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
</head>
<body>
    <header>
        <div class="nav">
            <a href="{% url 'index' %}" class="back-link"><img src="{% static 'accounts/images/back_icon.svg' %}" alt="back_icon"></a>
            <a href="{% url 'accounts:login' %}" class="login-link">Log In</a>
        </div>
    </header>
    <main>
        <div class="logo">
            <img src="{% static 'accounts/images/logo_1.svg' %}" alt="portfolia logo">
        </div>

        <h3 id="header">Create Your Account</h3>

        <!-- <a href="#"><img src="images/google_icon.svg" alt="google-icon"><p>Continue with Google</p></a> -->
        <div class="gbtn-container">
            <button class="google-btn" ><img src="{% static 'accounts/images/google_icon.svg' %}" alt="google-icon"> <a href="{% provider_login_url 'google' method = 'oauth2' %}">Continue with Google</a></button>
        </div>
        
        <div class="fbtn-container">
            <button class="facebook-btn" ><img src="{% static 'accounts/images/facebook_icon.svg' %}" alt="facebook-icon"><a href="{% provider_login_url 'facebook' method = 'js_sdk' %}">Continue with Facebook</a></button>
        </div>
        <!-- <a href="#" class="facebook-btn"><img src="images/facebook_icon.svg" alt="facebook-icon">Connect with Facebook</a> -->
       
       

        <h4 class="">Or</h4>

        {% comment %} {% if messages %}

        {% for message in messages %}

        <div class="error-message">

            <p>{{message}}</p>


        </div>


        {% endfor %}


        {% endif %} {% endcomment %}


        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                    {{ message|safe }}
                    <a href="{% url 'accounts:signup' %}" class="close">x</a>
                </li>
            {% endfor %}
        </ul>
        {% endif %}



        <form action="#" class = "signup-form"  method="POST">
            {% csrf_token %}
            <label for="first_name" >First Name</label><br>
            <input type="text" placeholder="John" name ="first_name" id="first_name" value="{{data.first_name}}" required><br>

            <label for="first_name" >Last Name</label><br>
            <input type="text" placeholder="Doe" name ="last_name" id="last_name" value="{{data.last_name}}" required><br>

            <label for="email" >Email</label><br>
            <input type="email" placeholder="name@email.com" name ="email" id="email" value="{{data.email}}" required><br>

            <label for="password" >Password</label><br>
            <input type="password" placeholder="Password" name ="password" id="password" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2, 3}$" required><br>

            <label for="confirm_password" >Confirm Password</label><br>
            <input type="password" placeholder="Should match password" name ="password2" id="password2" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2, 3}$" required><br>

            <p class="terms"> By creating an account, you agree to the <a href="#">Terms of service</a> and have read and understood the <a href="#">Privacy Policy</a></p><br>

            <input type="submit" value="Create account">

        </form>

        <p class="captcha">Secure Login with reCAPTCHA subject to <a href="#">Google Terms</a> & <a href="#">Privacy</a> </p>



    </main>
</body>
</html>